Create training flow
KotlinR/InAction pull request #1
Opened 2022-12-01 20:22 UTC by VadimRazzhivin

Implemented
- Trainings screen
- Create/Edit training screen

2022-12-02 15:40 UTC, pavelkharetskifreshly requested changes
Сделал первый поверхностный просмотр твоего кода.
Много чего надо передалать:
- ужасно сверстаны лейауты
- мешанина в котлин коде
- грубые ошибки при использовании Android SDK

На потом:
- надо будет вынести работу с БД из активити во вьюмодель в фоновый поток, отделить слой данных от слоя представления.

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/build.gradle
> +        applicationId "com.example.abox"
Нужен валидны applicationId, без слова образец/пример `example`

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/build.gradle
> +        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
Можно удалить, если не планируешь инструментальные тесты писать

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/build.gradle
> +            minifyEnabled false
В релизном билде минификация должна быть включена

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/build.gradle
> +            minifyEnabled false
И тогда signingConfigs надо добавить

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/build.gradle
> +        jvmTarget = '1.8'
JavaVersion.VERSION_1_8.toString() вместо хардкода

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
Все тестовые зависимости можно убрать, т.к. тестов нет

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/AndroidManifest.xml
> +            android:name=".MainActivity"
MainActivity - имя так себе, выбери что-нибудь по тематике приложения

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        const val DELETE_ALL_ID = 2
Сделай enum class

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        val allTrainings = fetchTrainings()
На каждый onResume (например после разблокировки экрана) будет происходить запрос в БД. Тут требуется пояснение от тебя о надобности фетча в этом коллбеке

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +            }
Пустые блоки удаляй, либо пиши TODO

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +                if (db?.getAllTrainings()?.count != 0) {
count != 0 -> isNotEmpty()

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        fetchTrainings().forEach {
TrainingActivity Сам должен фетчить из базы то, что ему нужно. И вообще, TrainingActivity же показывает одну тренировку, зачем ему все заголовки

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        intent.putStringArrayListExtra("allTitleTrainings", allTitlesTrainings)
Это явно лишнее, мы обсуждали, что передавать на экран создания/редактирования тренировки надо только одну тренировку, либо ее id

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/BoxerMovementLibrary.kt
> +class BoxerMovementLibrary : AppCompatActivity() {
BoxerMovementLibrary - invalid name, где постфикс Activity?

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/MainActivity.kt
> +            startActivity(Intent(this, BoxerMovementLibrary().javaClass))
BoxerMovementLibrary().javaClass) - полный бред, почитай, как пользоваться интентом

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/MainActivity.kt
> +            startActivity(Intent(this, AllTrainingsActivity().javaClass))
AllTrainingsActivity().javaClass) - двойной бред

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +        const val DELETE_TRAINING_ID = 3
попробуй сделать enum class

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +        allTitlesTrainings = intent.getStringArrayListExtra("allTitleTrainings")
Фетчить надо в этом активити, а не передавать извне

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +                            && allTitlesTrainings?.contains(trainingTitle?.text) == false -> {
Проверка должна быть реализована на уровне SQL

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +                            && (allTitlesTrainings?.contains(trainingTitle?.text) == false
Проверка должна быть реализована на уровне SQL
(allTitlesTrainings?.contains(trainingTitle?.text) == false

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
Слишком длинная функция

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +    override fun onOptionsItemSelected(item: MenuItem): Boolean {
Декомпозируй. Функция слишком сложная

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/adapter/RoundsRecycleAdapter.kt
> +
Лишний пробел

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/adapter/TrainingsRecyclerAdapter.kt
> +            onClick = onClick
trailing comma

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/java/com/example/abox/db/DBManager.kt
> +class DBManager(private val context: Context) {
работа с базой данных должна происходить в фоновом потоке. Но это в другом ПРе.

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/all_trainings_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Выровняй файл

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/boxer_movement_library.xml
> +        <TextView
Полностью неверный подход. У тебя список движений должен храниться в БД или оперативной памяти и ты динамически должен создавать список. У тебя дичайший хардкод. Совершенно негибко.

ПЕРЕДЕЛАТЬ !!!

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/confirmation_dialog.xml
> +    <LinearLayout
Если у тебя есть ConstraintLayout, то другие лейауты не нужны внутри.

ПЕРЕДЕЛАТЬ

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/enter_text_dialog.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Если у тебя есть ConstraintLayout, то другие лейауты не нужны внутри.

ПЕРЕДЕЛАТЬ

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/round_and_exercises.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Если у тебя есть ConstraintLayout, то другие лейауты не нужны внутри.

ПЕРЕДЕЛАТЬ

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/round_task.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Используй ConstraintLayout

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/training_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Оптимизируй лейаут

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/layout/training_title.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Тоже самое. Переделай лейаут

2022-12-02 15:40 UTC, pavelkharetskifreshly commented on abox/src/main/res/menu/menu_workout.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android">
Выровняй файл

2022-12-02 15:45 UTC, PashaJavaProgrammist requested changes
Комменты с другого акка

2022-12-02 15:46 UTC, PashaJavaProgrammist requested changes
‼️

2022-12-03 11:49 UTC, VadimRazzhivin commented on abox/build.gradle
> +        applicationId "com.example.abox"
исправлено
теперь com.sport.abox

2022-12-03 11:50 UTC, VadimRazzhivin commented on abox/build.gradle
> +        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
Не планировал. Удалил

2022-12-03 12:23 UTC, VadimRazzhivin commented on abox/build.gradle
> +        jvmTarget = '1.8'
sourceCompatibility тоже?

2022-12-03 12:24 UTC, VadimRazzhivin commented on abox/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
testImplementation 'junit:junit:4.13.2'
 androidTestImplementation 'androidx.test.ext:junit:1.1.3'
 androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

Убрал

2022-12-03 12:25 UTC, VadimRazzhivin commented on abox/build.gradle
> +            minifyEnabled false
хз куда там добавлять

release {
            minifyEnabled true
            signingConfigs
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

2022-12-03 12:28 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +            android:name=".MainActivity"
этот класс добавил ради того, что бы попрактиковаться
думаю его вообще удалить, т.к. не вижу смыла добавлять, по объективным причинам

2022-12-03 12:57 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        const val DELETE_ALL_ID = 2
сделал

2022-12-03 13:03 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        val allTrainings = fetchTrainings()
скорее всего не правильно выбрал, и тут лучше onRestart
задумка была следующая: изменив тренировку, или сохранив новую и вернувшись на экран со списком всех тренировок я хочу что бы произошло обновление этого списка (т.к. я мог удалить тренировку, добавить новую, внести изменения в существующую(новое название, добавил раундов и т.д.))

2022-12-03 13:11 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +                if (db?.getAllTrainings()?.count != 0) {
ты уверен? я не совсем понимаю как к курсору прикрутить isNotEmpty()

2022-12-03 13:14 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        fetchTrainings().forEach {
список созданных тренировок нужен что бы не сохранить новую тренировку м именем дубликатом(что бы не было одинаковых названий)

2022-12-03 13:16 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/BoxerMovementLibrary.kt
> +class BoxerMovementLibrary : AppCompatActivity() {
исправил

2022-12-03 13:17 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/MainActivity.kt
> +            startActivity(Intent(this, BoxerMovementLibrary().javaClass))
:: class.java
исправил

2022-12-03 13:21 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/MainActivity.kt
> +            startActivity(Intent(this, AllTrainingsActivity().javaClass))
очевидно же, что я так писал до того как ты мне объяснил

2022-12-03 13:21 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +        const val DELETE_TRAINING_ID = 3
закинул в ранее созданный энам класс и из разных активити обращаюсь к нему на прямую

2022-12-03 13:24 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +        allTitlesTrainings = intent.getStringArrayListExtra("allTitleTrainings")
думаю сначала надо вынести отдельно БД как мы с тобой оговаривали. и уже тогда думать как тут что фетчить и т.д. иначе тут можно знатно нахуевертить и у тебя опять кровь из глаз пойдет

2022-12-03 13:26 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +                            && allTitlesTrainings?.contains(trainingTitle?.text) == false -> {
имеешь ввиду что в DBHelpere надо соответствующий метод имплементировать?

2022-12-03 13:30 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
хз что ответить. дукав я не жалею)

2022-12-03 13:33 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +    override fun onOptionsItemSelected(item: MenuItem): Boolean {
тоже момент с БД. может лучше сначала с ней разобраться и от нее уже плясать? 
и тут хотел с тобой поговорить на тему сохранения. в общем нужно обговорить, что бы избежать очередного перемудрения

2022-12-03 13:34 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/adapter/RoundsRecycleAdapter.kt
> +
убрал

2022-12-03 13:35 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/adapter/TrainingsRecyclerAdapter.kt
> +            onClick = onClick
добаил

2022-12-03 13:36 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/db/DBManager.kt
> +class DBManager(private val context: Context) {
+++

2022-12-03 13:42 UTC, VadimRazzhivin commented on abox/src/main/res/layout/all_trainings_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+

2022-12-03 13:46 UTC, VadimRazzhivin commented on abox/src/main/res/layout/boxer_movement_library.xml
> +        <TextView
писал выше для класса работающего в связке с этим лэйаутом. было сделано в начале. для практики. жизнь этого активи под вопросом
в остальном, что должно быть в ДБ и т.д. я тебя полностью понял и понимаю для чего и почем это хардкор 
Думаю тоже с тобой на созвоне решить нужна ли вообще такая фича как бибилиотека с движениями

2022-12-03 13:56 UTC, VadimRazzhivin commented on abox/src/main/res/layout/confirmation_dialog.xml
> +    <LinearLayout
+++

2022-12-03 14:01 UTC, VadimRazzhivin commented on abox/src/main/res/layout/enter_text_dialog.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+++

2022-12-03 14:07 UTC, VadimRazzhivin commented on abox/src/main/res/layout/round_and_exercises.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+++

2022-12-03 14:18 UTC, VadimRazzhivin commented on abox/src/main/res/layout/round_task.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
вражеский лэйаут, нигде не применялся, потому был беспощадно удалён и помножен на ноль

2022-12-03 14:28 UTC, VadimRazzhivin commented on abox/src/main/res/menu/menu_workout.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android">
+++

2022-12-03 15:04 UTC, VadimRazzhivin commented on abox/src/main/res/layout/training_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+++

2022-12-03 15:04 UTC, VadimRazzhivin commented on abox/src/main/res/layout/training_title.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+++

2022-12-03 15:41 UTC, VadimRazzhivin commented on abox/src/main/res/layout/training_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+++

2022-12-03 15:42 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +            }
+++

2022-12-03 15:43 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/AllTrainingsActivity.kt
> +        intent.putStringArrayListExtra("allTitleTrainings", allTitlesTrainings)
скорее всего проблема решится, когда будет иначе оформлена БД

2022-12-03 15:44 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +                            && (allTitlesTrainings?.contains(trainingTitle?.text) == false
скорее всего проблема решится, когда будет иначе оформлена БД

2022-12-03 15:44 UTC, VadimRazzhivin commented on abox/src/main/java/com/example/abox/TrainingActivity.kt
> +    override fun onOptionsItemSelected(item: MenuItem): Boolean {
скорее всего проблема решится, когда будет иначе оформлена БД

2022-12-04 10:16 UTC, PashaJavaProgrammist requested changes
Пачка поверхностных моментов. Надо пофиксить. Пока еще не запускал апп и не смотрел логику.

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/build.gradle
> +        jvmTarget = '1.8'
Коммент на 31 строчку, ты поменял 28 - гениально. 👎
Хардкод здесь     ` jvmTarget = '1.8'`

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/build.gradle
> +
Лишняя пустая строка

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/AndroidManifest.xml
> +    package="com.example.abox">
Я же писал убрать `example`
У тебя уже другой applicationId (packageName)

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.MainActivity"
Достаточно просто .MainActivity если указан верный packageName

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.BoxerMovementLibraryActivity"
Достаточно просто .BoxerMovementLibraryActivity если указан верный packageName

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.AllTrainingsActivity"
Достаточно просто .AllTrainingsActivity если указан верный packageName

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.TrainingActivity"
Достаточно просто .TrainingActivity если указан верный packageName

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +            openTrainingScreen(null)
Добавь named arguments

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        val allTrainings = fetchTrainings()
Ты уверен, что это тут нужно? Точно знаешь, когда callback onRestart срабатывает?

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        menu?.add(0, ItemItMenu.SETTINGS_ID.index, 0, "Setting")
Должно выглядеть

menu?.add(0, Menu.SETTINGS.id, 0, Menu.SETTINGS.title)

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        menu?.add(0, ItemItMenu.DELETE_ALL_ID.index, 0, "Delete all")
аналогично

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +            ItemItMenu.SETTINGS_ID.index -> {
аналогично

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        val allTitlesTrainings = arrayListOf<String>()
Почему arrayListOf? Аргументируй

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        intent.putExtra("training", training)
"training" должно быть вынесено в константы. Одна константа ключа для put и get значения из интента

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        intent.putStringArrayListExtra("allTitleTrainings", allTitlesTrainings)
Это лишний параметр. Описывал в предыдущем ревью

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/ItemItMenu.kt
> +enum class ItemItMenu(val index: Int) {
👎

enum class TrainingMenu(val id: Int, val title: String)

Что-то такое должно быть.

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +        val training = intent.getParcelableExtra<Training>("training")
Хардкод в константы

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +        allTitlesTrainings = intent.getStringArrayListExtra("allTitleTrainings")
Хардкод в константы

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            EDIT_TITLE_DIALOG_TYPE -> {
_TYPE - лишнее, удали из названия констант этот постфикс

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/adapter/RoundsRecycleAdapter.kt
> +            roundOfTraining.text = "Round [ ${position.plus(1)} ]"
position.plus(1)
position + 1 - а так что, не работает?

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/dialogs/EnterTextDialog.kt
> +            key = KEY_NEU,
KEY_NEU -> KEY_NEUTR

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/res/layout/activity_main.xml
> +    <LinearLayout
Лишний LinearLayout

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/res/layout/boxer_movement_library.xml
> +        <TextView
Не будешь переделывать - тогда удаляй. Такому коду в мастере не место

2022-12-04 10:16 UTC, PashaJavaProgrammist commented on abox/src/main/res/layout/training_activity.xml
> +
Лишняя строка

2022-12-04 10:22 UTC, VadimRazzhivin commented on abox/build.gradle
> +        jvmTarget = '1.8'
исправил

2022-12-04 10:25 UTC, VadimRazzhivin commented on abox/build.gradle
> +
убрал

2022-12-04 10:26 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +    package="com.example.abox">
убрал

2022-12-04 10:27 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.MainActivity"
+++

2022-12-04 10:27 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.BoxerMovementLibraryActivity"
+++

2022-12-04 10:28 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.AllTrainingsActivity"
+++

2022-12-04 10:28 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +            android:name="com.sport.abox.TrainingActivity"
+++

2022-12-04 10:30 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +            openTrainingScreen(null)
+++

2022-12-04 10:36 UTC, PashaJavaProgrammist requested changes
Еще пачка фиксов

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/adapter/TrainingsRecyclerAdapter.kt
> +    fun updateTrainings(allTrainings: List<Training>) {
@SuppressLint("NotifyDataSetChanged")

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/dialogs/ConfirmationDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
`private fun createButton(id: Int, key: String, onClick: (View) -> Unit) {
view?.findViewById<Button>(id)?.apply {
arguments?.getString(key)?.let {
text = it
setOnClickListener(onClick)
} ?: run { visibility = View.GONE }
}
}`

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/dialogs/EnterTextDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
onClick: (View) -> Unit

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/dialogs/EnterTextDialog.kt
> +                }
setOnClickListener(onClick)

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/dialogs/ConfirmationDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
Название лучше setUpButton, ты же не создаешь, а настраиваешь кнопку. Также функция повторяется в другом диалоге, вынеси как extension

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        findViewById<FloatingActionButton>(R.id.btnAddTraining).setOnClickListener {
Я предпочитаю выносить кнопки в поля классы

`private val fab by lazy {
findViewById<FloatingActionButton>(R.id.btnAddTraining)
}`

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        findViewById<FloatingActionButton>(R.id.btnAddTraining).setOnClickListener {
Тоже самое с recyclerView

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/MainActivity.kt
> +        val btnLibrary = findViewById<Button>(R.id.btnLibrary)
Сделай переменным класса через делегат lazy

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            originTraining = training
training тут всегда null. originTraining и так null. Строку можно удалить

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            originTraining = training
16 в константы

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            originTraining = training
Все строки надо будет вынести в ресурсы и обращать через R.string.string_id

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/res/layout/confirmation_dialog.xml
> +        android:text="TextView"
tools:text

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/res/layout/confirmation_dialog.xml
> +        android:layout_weight="1"
layout_weight не используется в ConstraintLayout. Проверь все лейауты.

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/res/layout/enter_text_dialog.xml
> +        android:layout_weight="1"
👎

2022-12-04 10:36 UTC, PashaJavaProgrammist commented on abox/src/main/res/menu/menu_workout.xml
> +
Лишняя строка. Приведи файл в порядок

2022-12-04 11:07 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        val allTrainings = fetchTrainings()
чот начал вчитываться и смотреть логи сделанных уроков с жизненными циклами и везде кажется хуета и хз как лучше впихнут
возникла мысль это обыграть через onActivityResult

2022-12-04 11:14 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        menu?.add(0, ItemItMenu.SETTINGS_ID.index, 0, "Setting")
сделал

2022-12-04 11:14 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        menu?.add(0, ItemItMenu.DELETE_ALL_ID.index, 0, "Delete all")
сделал

2022-12-04 11:16 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +            ItemItMenu.SETTINGS_ID.index -> {
вот тут не понял.
поменять с index на title?

2022-12-04 11:19 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        val allTitlesTrainings = arrayListOf<String>()
тут тоже всё решится когда БД будет реализована как надо. и тогда эту ересь вообще  можно будет убрать

2022-12-04 11:24 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        intent.putExtra("training", training)
вынес в этом же файле
но, вроде как-то говорили с тобой на эту тему и ты сказал что можно подобные константы вынести в отдельный файл ?

2022-12-04 11:24 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        intent.putStringArrayListExtra("allTitleTrainings", allTitlesTrainings)
да, всё порешается с "новой" БД

2022-12-04 11:25 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/ItemItMenu.kt
> +enum class ItemItMenu(val index: Int) {
сделано

2022-12-04 11:25 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +        val training = intent.getParcelableExtra<Training>("training")
сделано

2022-12-04 11:26 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +        allTitlesTrainings = intent.getStringArrayListExtra("allTitleTrainings")
всё порешается с "новой" БД

2022-12-04 11:27 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            EDIT_TITLE_DIALOG_TYPE -> {
+++

2022-12-04 11:28 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/adapter/RoundsRecycleAdapter.kt
> +            roundOfTraining.text = "Round [ ${position.plus(1)} ]"
+++

2022-12-04 11:29 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/dialogs/EnterTextDialog.kt
> +            key = KEY_NEU,
+++

2022-12-04 11:38 UTC, VadimRazzhivin commented on abox/src/main/res/layout/activity_main.xml
> +    <LinearLayout
+++

2022-12-04 11:39 UTC, VadimRazzhivin commented on abox/src/main/res/layout/training_activity.xml
> +
+++

2022-12-04 19:17 UTC, PashaJavaProgrammist requested changes
Начал смотреть и понял, что половину комментов ты проигнорил. Так не пойдет. Читай внимательно.

2022-12-04 19:17 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        intent.putStringArrayListExtra("allTitleTrainings", allTitlesTrainings)
Это тут не при чем. Это сейчас надо фиксить. Передаваться должна только одна тренировка‼️

2022-12-04 19:17 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/ItemIsMenu.kt
> +enum class ItemIsMenu(val index: Int, val title: String) {
Я же тебе написал нормальное название до этого. Текущее - бред

2022-12-04 19:17 UTC, PashaJavaProgrammist commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +        allTitlesTrainings = intent.getStringArrayListExtra("allTitleTrainings")
Не пиши бред

2022-12-06 10:09 UTC, VadimRazzhivin commented on abox/src/main/AndroidManifest.xml
> +            android:name=".MainActivity"
удалил

2022-12-06 10:12 UTC, VadimRazzhivin commented on abox/src/main/res/layout/all_trainings_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
выровнял

2022-12-06 10:12 UTC, VadimRazzhivin commented on abox/src/main/res/layout/boxer_movement_library.xml
> +        <TextView
удалил

2022-12-06 10:14 UTC, VadimRazzhivin commented on abox/src/main/res/layout/enter_text_dialog.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
переделал

2022-12-06 10:14 UTC, VadimRazzhivin commented on abox/src/main/res/layout/round_and_exercises.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
переделал

2022-12-06 10:15 UTC, VadimRazzhivin commented on abox/src/main/res/layout/training_activity.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
сделал

2022-12-06 10:16 UTC, VadimRazzhivin commented on abox/src/main/res/layout/training_title.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
сделал

2022-12-06 10:16 UTC, VadimRazzhivin commented on abox/src/main/res/menu/menu_workout.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android">
сделал

2022-12-06 10:19 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        intent.putStringArrayListExtra("allTitleTrainings", allTitlesTrainings)
убрал

2022-12-06 10:22 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +        allTitlesTrainings = intent.getStringArrayListExtra("allTitleTrainings")
перенес

2022-12-06 10:22 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/adapter/TrainingsRecyclerAdapter.kt
> +    fun updateTrainings(allTrainings: List<Training>) {
добавил

2022-12-06 10:22 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/dialogs/ConfirmationDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
сделал

2022-12-06 10:23 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/dialogs/EnterTextDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
исправил

2022-12-06 10:24 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/dialogs/EnterTextDialog.kt
> +                }
исправил

2022-12-06 10:24 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/dialogs/ConfirmationDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
поменял

2022-12-06 10:40 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/dialogs/ConfirmationDialog.kt
> +    private fun createButton(id: Int, key: String, onClick: () -> Unit) {
вынес как extension

2022-12-06 10:43 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/AllTrainingsActivity.kt
> +        findViewById<FloatingActionButton>(R.id.btnAddTraining).setOnClickListener {
бахнул

2022-12-06 10:46 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/MainActivity.kt
> +        val btnLibrary = findViewById<Button>(R.id.btnLibrary)
Сделал

2022-12-06 10:47 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            originTraining = training
удалил

2022-12-06 10:48 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            originTraining = training
не понял

2022-12-06 10:50 UTC, VadimRazzhivin commented on abox/src/main/res/layout/confirmation_dialog.xml
> +        android:text="TextView"
исправил

2022-12-06 10:51 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/TrainingActivity.kt
> +            originTraining = training
это можно сделать в будущем?

2022-12-06 10:53 UTC, VadimRazzhivin commented on abox/src/main/res/menu/menu_workout.xml
> +
убрал

2022-12-06 10:53 UTC, VadimRazzhivin commented on abox/src/main/res/layout/enter_text_dialog.xml
> +        android:layout_weight="1"
убрал

2022-12-06 10:53 UTC, VadimRazzhivin commented on abox/src/main/res/layout/confirmation_dialog.xml
> +        android:layout_weight="1"
убрал

2022-12-06 10:59 UTC, VadimRazzhivin commented on abox/src/main/java/com/sport/abox/ItemIsMenu.kt
> +enum class ItemIsMenu(val index: Int, val title: String) {
на название не обратил внимание. исправил

2023-01-24 07:48 UTC, PashaJavaProgrammist approved these changes
Вмержим этот ПР.
Отрефакторим код в будущем

2023-01-24 07:49 UTC, merged